# Generated by Django 2.2.7 on 2019-11-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
